//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailChannel
    {
        public int IdChannel { get; set; }
        public int IdBusStation { get; set; }
        public Nullable<int> Time { get; set; }
        public string Note { get; set; }
    
        public virtual BusStation BusStation { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
