//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int IdOrderDetail { get; set; }
        public int IdOrder { get; set; }
        public int IdSchedule { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> FloorNumber { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
